language: java
dist: trusty
sudo: false

script:
  - ./gradlew --scan build -Pjunit4Version=4.10  -PjunitJupiterVersion=5.5.0-RC2 -PskipSpotBugs
  - ./gradlew --scan build -Pjunit4Version=4.11  -PjunitJupiterVersion=5.5.0     -PskipSpotBugs
  - ./gradlew --scan build

  - cd ${TRAVIS_BUILD_DIR}/junit4/
  - mvn test
#  - ant test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter/
  - mvn test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter-params/
  - mvn test

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - ./gradlew --scan jacocoRootReport coveralls
