language: java

script:
  - ./gradlew build -Pjunit4Version=4.8.2 -PjunitJupiterVersion=5.0.0-M6  -PskipFindBugs
  - ./gradlew build -Pjunit4Version=4.9   -PjunitJupiterVersion=5.0.0-RC2 -PskipFindBugs
  - ./gradlew build -Pjunit4Version=4.10  -PjunitJupiterVersion=5.0.0-RC3 -PskipFindBugs
  - ./gradlew build -Pjunit4Version=4.11  -PjunitJupiterVersion=5.0.0     -PskipFindBugs

  - ./gradlew build

  - cd ${TRAVIS_BUILD_DIR}/junit4/
  - mvn test
#  - ant test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter/
  - mvn test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter-params/
  - mvn test

jdk:
  - oraclejdk8

dist: precise

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - ./gradlew jacocoTestReport coveralls

sudo: false
