language: java
dist: trusty
sudo: false

script:
  - ./gradlew build -Pjunit4Version=4.10  -PjunitJupiterVersion=5.4.0 -PskipSpotBugs
  - ./gradlew build -Pjunit4Version=4.11  -PjunitJupiterVersion=5.4.2 -PskipSpotBugs

  - ./gradlew build

  - cd ${TRAVIS_BUILD_DIR}/junit4/
  - mvn test
#  - ant test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter/
  - mvn test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter-params/
  - mvn test

jdk:
  - oraclejdk8
  - oraclejdk9

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - ./gradlew jacocoRootReport coveralls
